spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: false
  datasource:
    password:
    url: jdbc:h2:mem:paymentDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    driverClassName: org.h2.Driver
  flyway:
    enabled: false
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 8080